server:
  port: 8080
  servlet:
    context-path: /
  session:
    timeout: 30m
  
spring:
  application:
    name: totp-receiver
 
logging:
  level:
    com.example.totp.receiver: DEBUG
    root: INFO
    