server:
  port: 8081
  servlet:
    context-path: /
  session:
    timeout: 30m

spring:
  application:
    name: totp-receiver

logging:
  level:
    com.example.totp.receiver: DEBUG
    root: INFO

api:
  totpReceiver:
    url: http://host.docker.internal:8080